### PR TITLE
update to the current ecosystem

### PR DESCRIPTION
**Pull request by hannesm**

### CODE REVIEW

**Comment by sg2342** [comment]
I experienced one issue:

the command
```
( opam switch -q --color=never create mirage-block-ccm 4.14.0 &&
  opam pin -q --color=never --switch=mirage-block-ccm \
     add -y 'https://github.com/hannesm/mirage-block-ccm.git#new'; ) > /tmp/output.txt 2>&1
```

fails:
```
[ERROR] The compilation of mirage-block-ccm failed at "/home/sg/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-block-ccm -j 3".

#=== ERROR while compiling mirage-block-ccm.1.0.1 =============================#
# context              2.0.8 | linux/x86_64 | ocaml-base-compiler.4.14.0 | pinned(git+https://github.com/hannesm/mirage-block-ccm.git#new#05d59ce9)
# path                 ~/.opam/mirage-block-ccm/.opam-switch/build/mirage-block-ccm.1.0.1
# command              ~/.opam/opam-init/hooks/sandbox.sh build dune build -p mirage-block-ccm -j 3
# exit-code            1
# env-file             ~/.opam/log/mirage-block-ccm-109342-ab26c6.env
# output-file          ~/.opam/log/mirage-block-ccm-109342-ab26c6.out
### output ###
# [...]
# -> required by _build/default/META.mirage-block-ccm
# -> required by _build/install/default/lib/mirage-block-ccm/META
# -> required by _build/default/mirage-block-ccm.install
# -> required by alias install
# File "examples/dune", line 5, characters 3-25:
# 5 |    mirage-crypto-rng.unix))
#        ^^^^^^^^^^^^^^^^^^^^^^
# Error: Library "mirage-crypto-rng.unix" not found.
# -> required by _build/default/examples/ccmblock.exe
# -> required by _build/install/default/bin/ccmblock
# -> required by _build/default/mirage-block-ccm.install
# -> required by alias install
```

the complete output.txt is in [here](https://gist.github.com/sg2342/4581aba7a253fec25e4ce8407e5ce67f#file-output-txt-L122)

I think the example code should be contained in a package variant (-unix?) that requires the needed dependencies or if this is to much effort: disconnected from the build.

**Comment by hannesm** [comment]
In [eaa3a4b](https://github.com/sg2342/mirage-block-ccm/pull/24/commits/eaa3a4b654bddc3b07f7428c7edc87b841bf611a) the dependencies are more correct, and examples/ccmblock is marked as optional.

In [9341c23](https://github.com/sg2342/mirage-block-ccm/pull/24/commits/9341c237c14d6ba703a22c44252634cf2483b088) a CI based on GitHub actions is added. Once that is in the main branch, the GitHub action will trigger on each push and PR.

**Comment by hannesm** [comment]
FWIW: releasing opam package that use dune is nicely supported by `opam install dune-release` and then `dune-release tag && dune-release bistro` :)

**Comment by sg2342** [comment]
> FWIW: releasing opam package that use dune is nicely supported by `opam install dune-release` and then `dune-release tag && dune-release bistro` :)

will do. 
any opinion on the version to use? is `1.0.2` o.k.

**Comment by hannesm** [comment]
Yes, 1.0.2 sounds good.

**Pull request merged**
